In [51]:
import numpy as np

In [52]:
# joining 2 arrays with concatenate
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate((x, y)))
np.concatenate([x, y])

[1 2 3 3 2 1]


array([1, 2, 3, 3, 2, 1])

In [53]:
# joining > 2 arrays at once
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [54]:
# concatenate 2 dimensional arrays
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [55]:
# concatenate along first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [56]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [57]:
# for mixed dimensions use vstack and hstack
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [58]:
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [ ]:
# splitting arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

In [ ]:
# hsplit and vsplit
grid = np.arange(16).reshape((4, 4))
grid

In [ ]:
# split the 4x4 array vertically
upper, lower = np.vsplit(grid, [2]) 
print(upper)
print('')
print(lower)

In [ ]:
# split the 4x4 array horizontally
left, right = np.hsplit(grid, [2])
print(left)
print('')
print(right)