In [1]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# first 5 elements
print(x[:5])

In [ ]:
# elements after index 5
print(x[5:])

In [ ]:
# middle subarray
print(x[4:7])

In [ ]:
# every other element
print(x[::2])

In [ ]:
# every other element, starting at index 1
print(x[1::2])

In [ ]:
# reversed every other from index 5
print(x[5::-2])

In [ ]:
# all elements reversed
print(x[::-1])

In [2]:
############################################################
# multidimensional subarrays
x2 = np.random.randint(10, size=(3, 4))
print(x2)

[[1 1 3 1]
 [3 3 6 6]
 [0 9 9 0]]


In [ ]:
# access 2 rows 3 columns
print(x2[:2, :3])

In [ ]:
# all rows, every other column
print(x2[:3, ::2])

In [ ]:
# reverse all the values in an array
print(x2[::-1, ::-1])

In [5]:
# accessing array rows and columns
print('first column of x2:', x2[:, 0])
print('first row of x2:', x2[0, :])
# without specific instructions
print('first row od x2:', x2[0]) # equivalent to x2[0, :]

first column of x2: [1 3 0]
first row of x2: [1 1 3 1]
first row od x2: [1 1 3 1]


In [8]:
# subarrays
# array slices return views, whereas list slices return copies

# extract a 2x2 subarray
x2_sub = x2[:2, :2]
print('2x2 sub array of x2:\n', x2_sub)
print('')
# modify the array
x2_sub[0, 0] = 99
# change the first row and column array value to 99
# observe, it will change the original array
print('notice the original array changed:\n', x2)

2x2 sub array of x2:
 [[99  1]
 [ 3  3]]
notice the original array changed:
 [[99  1  3  1]
 [ 3  3  6  6]
 [ 0  9  9  0]]


In [10]:
# creating copies of arrays with copy method
x2_sub_copy = x2[:2, :2].copy()
print('2x2 copy of array x2:\n', x2_sub_copy)
# modify
x2_sub_copy[0, 0] = 42
print('subarray chengad:\n', x2_sub_copy)
# original array doesn't change at all
print('original array\n', x2)

2x2 copy of array x2:
 [[99  1]
 [ 3  3]]
subarray chengad:
 [[42  1]
 [ 3  3]]
original array
 [[99  1  3  1]
 [ 3  3  6  6]
 [ 0  9  9  0]]
