In [9]:
import numpy as np

In [10]:
# the simplest way to reshape a an array in 1 line
grid = np.arange(1, 10).reshape((3, 3))
print('directly reshaped:\n', grid)

directly reshaped:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
x = np.array([1, 2, 3])

print(x)
# raw vector via reshape
print('reshaped:\n', x.reshape((1, 3)))

# row vector via newaxis
xnewaxis = x[np.newaxis, :]
print('row vector via newaxis\n', xnewaxis)

[1 2 3]
reshaped:
 [[1 2 3]]
row vector via newaxis
 [[1 2 3]]


In [12]:
# columns vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [13]:
# column vecotr via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])