In [4]:
from scipy import special
import numpy as np

In [2]:
# gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [5]:
# Error function (integral of gaussian), its complement and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)    =", special.erf(x))
print("erfc(x)   =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)    = [0.         0.32862676 0.67780119 0.84270079]
erfc(x)   = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


In [6]:
# write results directly to specified memory location
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [8]:
# even more specific
# to save even more memory use this technique
y = np.zeros(10)
np.power(2, x, out=y[::2])
# the "out argument specify the target array"
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [12]:
# aggregates
x = np.arange(1, 6)
print(x)
print(np.add(x, x))
print(np.add.reduce(x))
print(np.multiply.reduce(x))

[1 2 3 4 5]
[ 2  4  6  8 10]
15
120


In [13]:
# store all the results
print(np.add.accumulate(x))
print(np.multiply.accumulate(x))

[ 1  3  6 10 15]
[  1   2   6  24 120]


In [14]:
print(np.__version__)

1.18.1


In [15]:
# outer products
print(np.multiply.outer(x, x))

[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]
